name: Compile CV

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-upload-cv:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: CV.tex 
          latexmk_args: -pdf

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: CV
          path: CV.pdf
